<a href="https://colab.research.google.com/github/SejalJadhav1/python_/blob/main/MachineLearningTechnique_test_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split 
import random
from sklearn.linear_model import Ridge, Lasso

In [ ]:
x = np.zeros(5)

In [ ]:
x = np.column_stack((np.ones(x.shape[0]) , x ))
x


array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [ ]:
x =np.column_stack((np.ones(x.shape[0]) , x))
w = np.array([[1,2],[3,4],[5,6]])


NameError: ignored

In [ ]:
w.sum()

21

In [ ]:
l = []
for i , j in w:
  l.append(j)
l  

[2, 4, 6]

In [ ]:
def loss(x, y, w, lr):
  x = np.column_stack((np.ones(x.shape[0]) , x ))
  e = (x @ w)-y
  ridge_loss = (1/2) * ((e.T) @ e) + (lr/2) ((w.T)@w)  
  lasso_loss = (1/2)((x @ w)-y).T((x @ w)-y) + (lr/2) * w.sum()

  if ridge_loss>lasso_loss:
    return lasso_loss
  else:
    return ridge_loss  


def loss1(x, y, w, lr):
  e = y - (x @ w)
  x = np.column_stack((np.ones(100) , x ))
  ridge_loss = (1/2) * (np.transpose(e) @ e) + (lr/2) * (np.transpose(w)@w)  
  lasso_loss = (1/2) * (np.transpose(e) @ e) + (lr/2) * (w.sum())
  if ridge_loss > lasso_loss:
      return lasso_loss
  else:
      return ridge_loss 

# (100 x 5), (100 x 1) and (6 x 1)

In [ ]:
x = np.array(np.random.rand(100 , 5))
y = np.array(np.random.rand(100 , 1))
w = np.ones(x.shape[1])
lr = 0.1

In [ ]:
e = y - (x @ w)
x = np.column_stack((np.ones(100) , x ))
e = y - (x @ w)

x.shape
ridge_loss = (1/2) * (np.transpose(e) @ e) + (lr/2) * (np.transpose(w)@w)
ridge_loss

ValueError: ignored

In [ ]:
s

In [ ]:
def is_binary(y): 
  if np.count_nonzero(np.unique(y))==2:
      return True
  else:
      return False

In [ ]:
def is_binary(y): 
  a = np.unique(y)
  count = 0
  for i in range(1,):
    y.index(i)
    

In [ ]:
y = np.array([0, 6 , 11])
np.bincount(y)

In [ ]:
np.unique(y).shape[0]

In [ ]:
la = Lasso(alpha = 0.01)
la.fit(x,y)
la.score(x,y)

In [ ]:
loss1(x, y, w, reg_rate)

In [ ]:
x = np.array(np.random.rand(100 , 5))
y = np.array(np.random.rand(100 , 1))
w = np.ones(x.shape[1])
lr = 0.1

In [ ]:
loss1(x, y, w, lr)

In [ ]:
x.shape[0]

In [ ]:
x = np.column_stack((np.ones(x.shape[0]) , x ))
x.shape

In [ ]:
w

In [ ]:
e = x@w
e.shape
e

In [ ]:
e = (x@w) - y
e.shape

In [ ]:
import numpy as np

def compute_confusion_matrix(true, pred):
  '''Computes a confusion matrix using numpy for two np.arrays
  true and pred.

  Results are identical (and similar in computation time) to: 
    "from sklearn.metrics import confusion_matrix"

  However, this function avoids the dependency on sklearn.'''

  K = len(np.unique(true)) # Number of classes 
  result = np.zeros((K, K))

  for i in range(len(true)):
    result[true[i]][pred[i]] += 1

  return result

In [ ]:
def confusionMatrix(actual, pred):
  TP = (actual==pred)[actual].sum()
  TN = (actual==pred)[~actual].sum()
  FP = (actual!=pred)[~actual].sum()
  FN = (actual!=pred)[actual].sum()

  return [[TP, TN], [FP, FN]]

In [ ]:
confusionMatrix(y, ypred)

In [ ]:
actual = np.array([1 , 2 ,3 , 3 , 5])
pred = np.array([1 , 2 , 2 , 2 , 4])

In [ ]:
y 

In [ ]:
actual =actual.reshape(1,5)

In [ ]:
y.shape

In [ ]:
pred = pred.reshape(1,5)

In [ ]:
TP = (actual==pred)[actual].sum()

In [ ]:
actual==pred

In [ ]:
def confusion_matrix(actual, predicted):
  classes = np.unique(np.concatenate((actual,predicted)))
  confusion_mtx = np.empty((len(classes),len(classes)),dtype=np.int)
  for i,a in enumerate(classes):
      for j,p in enumerate(classes):
          confusion_mtx[i,j] = np.where((actual==a)*(predicted==p))[0].shape[0]
  return confusion_mtx

In [ ]:
confusion_matrix(actual, pred)

In [ ]:
def predict(x,w):
    x = np.column_stack((np.ones(x.shape[0]) , x))
    assert x.shape[-1]==w.shape[0]
    a = x@w
    return a

In [ ]:
def predict(X, w):
    if X.shape[1] == w.shape[0]:
        return X @ w
    else:
        return None

In [ ]:
def predict(x,w):
    x = np.column_stack((np.ones(x.shape[0]) , x))
    y = []
    for i in range(0 , x.shape[0]):
        yhat = 0
        for j in range(0 , x.shape[1]):
            yhat = yhat + x[i][j] * w[j]
        y.append(yhat)
    return np.array(y) 

In [ ]:
x = np.array(np.random.rand(5 , 5))
y = np.array(np.random.rand(5 , 1))
w = np.ones(x.shape[1])
lr = 0.1


In [ ]:
def loss(x,w,y):
    x = np.column_stack((np.ones(x.shape[0]) , x))
    loss = np.sum((predict(x,w)-y)**2)
    return loss

In [ ]:
x = np.column_stack((np.ones(x.shape[0]) , x))


In [ ]:
x.shape

(5, 6)

In [ ]:
w = np.ones(x.shape[1])
w.shape

(6,)

In [ ]:
x

array([[1.        , 0.28841278, 0.61398483, 0.14196384, 0.63252118,
        0.73565305],
       [1.        , 0.19680432, 0.63885363, 0.83674238, 0.30985915,
        0.82642873],
       [1.        , 0.54769004, 0.30500995, 0.7485619 , 0.48693647,
        0.26457371],
       [1.        , 0.79817112, 0.09711666, 0.26870521, 0.36581744,
        0.91952724],
       [1.        , 0.28535544, 0.19772916, 0.1029794 , 0.85028564,
        0.0559118 ]])

In [ ]:
y = np.array(np.random.rand(5 , 1))
y.shape


(5, 1)

In [ ]:
def predict(x,w):
    x = np.column_stack((np.ones(x.shape[0]) , x))
    if x.shape[1] == w.shape[0]:
        return x @ w
    else:
        return None
def loss(x,w,y):
    x = np.column_stack((np.ones(x.shape[0]) , x))
    e = predict(x,w)-y
    

In [ ]:
loss = np.sum((predict(x,w)-y)**2)

NameError: ignored

In [ ]:
e = 0.5 * np.sum((x@w - y)**2)


In [ ]:
import numpy as np

In [ ]:
def ConfusionMatrix(y_hat,y):
    a = np.unique(y)[0]
    b = np.unique(y)[1]
    TN = 0
    TP = 0
    FP = 0
    FN = 0

    for i,j in zip(y_hat ,y):
        if i == a and j==a :
            TN = TN+1
        elif i== b and j ==b:
            TP = TP+1
        elif i==a and j==b:
            FP = FP + 1
        elif i==b and j==a:
            FN = FN + 1
        else:
            return None
    return np.array([[TN , FP] , [FN , TP]] )   

In [ ]:
y_hat = np.array([5,1,1,1,5,1,5,1,5,1,1,1])
y = np.array([1,1,1,5,5,5,5,1,1,1,1,1])
np.unique(y)

array([1, 5])

In [ ]:
ConfusionMatrix(y_hat,y)

array([[6, 2],
       [2, 2]])

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_hat, y)



array([[6, 2],
       [2, 2]])

## MLT WEEK **2**

In [ ]:
def add_dummy_feature(x):
  return np.column_stack((np.ones(x.shape[0]) , x))

def predict(x,w):
  x = np.column_stack((np.ones(x.shape[0]) , x))
  if x.shape[-1]==w.shape[0]:
    y_pred = x@w
    return y_pred
  else:
    return None  

def non_vectorized_predict(x,w):
  x = np.column_stack((np.ones(x.shape[0]) , x))
  y = []
  for i in range(0 , x.shape[0]):
      yhat = 0
      for j in range(0 , x.shape[1]):
          yhat =  yhat + x[i][j] * w[j]
      y.append(yhat)
  return np.array(y) 

def loss(x,y,w):
  x = np.column_stack((np.ones(x.shape[0]) , x))
  if x.shape[-1] == w.shape[0]:
      e = x@w - y
      loss =0.5 * (np.transpose(e) @ e)
      return loss
  else:
      return None

def normal_equation(x,y):
  x = np.column_stack((np.ones(x.shape[0]) , x))
  if x.shape[-1] == w.shape[0]:
    return np.linalg.pinv(x)@y
  else:
    return None  

def calculate_gradient(x,y,w):
  x = np.column_stack((np.ones(x.shape[0]) , x))
  if x.shape[-1] == w.shape[0]:
    return np.transpose(x)@ ((x@w) -y)
  else:
    return None  

def weight_update(x,y,w,lr):
    x = np.column_stack((np.ones(x.shape[0]) , x))
    if x.shape[-1] == w.shape[0]:
      return w - lr * (np.transpose(x)@ ((x@w) -y))
    else:
      return None  

def gradient_descent(x, y, w,lr,epochs):
  losses = []
  weights = []
  x = np.column_stack((np.ones(x.shape[0]) , x))
  w = np.zeros((x.shape[1]))
  if x.shape[-1] == w.shape[0]:
    for i in range(epochs):
      e = x@w - y
      l =0.5 * (np.transpose(e) @ e)
      g = w - lr * (np.transpose(x)@ ((x@w) -y))
      losses.append(l)
      weights.append(g)
    return losses,weights  








In [ ]:
predict(x,w)

array([ 4.,  8., 12.])

In [ ]:
x = np.array([[1,2,] , [3,4] , [5,6]])
w = np.array([5,1,2])
y = np.array([2,3,4])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
gradient_descent(x,y ,w , 0.01 , 5)

([14.5, 14.5, 14.5, 14.5, 14.5],
 [array([0.09, 0.31, 0.4 ]),
  array([0.09, 0.31, 0.4 ]),
  array([0.09, 0.31, 0.4 ]),
  array([0.09, 0.31, 0.4 ]),
  array([0.09, 0.31, 0.4 ])])

In [ ]:
x.shape

(3, 2)

In [ ]:
for i in range(0 , x.shape[0]):
  l = []
  for j in range(0 , x.shape[1]):
      yhat =x[i][j]
      print(l.append(yhat))

None
None
None
None
None
None


In [ ]:
x[0][0]

1

In [ ]:
np.arange(0 , 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


## MLT WEEK **3**

In [ ]:

import itertools
import functools

def get_combinations(x , degree):
  return itertools.combinations_with_replacement(x , degree)

def compute_new_features(items):
  return functools.reduce(lambda x , y: x*y , items)

def polynomial_transform(x, degree):
  if x.ndim == 1:
    x = x[:, None]
    x_t = x.T

  features = [np.ones(len(x))] #a list of np-arrays with all 1.

  for i in range(1, degree + 1):
      for j in itertools.combinations_with_replacement(x , degree):
          features.append(functools.reduce(lambda x , y: x*y , j))
            
  return np.asarray(features).T

def model_error(X, y,degree):
    X = polynomial_transform(X,degree)
    w = np.linalg.inv(X.transpose()@X)@X.transpose()@y
    loss = (1/2)*(X@w - y).transpose()@(X@w-y)
    RMSE = np.sqrt((2/len(y))*loss)
    return RMSE  

def mean_abs(X,y,w):

    if X.shape[-1]==w.shape[0]:
        return np.mean(np.abs(X@w - y))    

def model_error(x, y,degree):
  from sklearn.linear_model import LinearRegression
  transformed_features = polynomial_transform(x, degree)
  polyreg = LinearRegression()
  w_nonlin = polyreg.fit(transformed_features, y)
  y_pred=w_nonlin.predict(polynomial_transform(x,degree))
  training_error=y_pred-y
  train_loss = (1/2) * (np.transpose(training_error) @ training_error) 
  rmse = np.sqrt((2/X.shape[0])*train_loss)
  return rmse  

In [ ]:
def poly(x , degree):
  if x.ndim==1:
    x = x[: , None]
    x = x.T
  features = [np.ones(x.shape[0])]
  for i in range(1 , degree+1):
    for j in get_combinations(x , degree):
      features.append(compute_new_features(j))   

In [ ]:
polynomial_transform(np.array([2, 3]),2)

[array([1.])]
(array([2, 3]),)
(array([2, 3]), array([2, 3]))
[array([1.]), array([2, 3]), array([4, 9])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:27: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.


array([array([1.]), array([2, 3]), array([4, 9])], dtype=object)

In [ ]:
features = [np.ones(len(x))]
for i in features:
  print(i)

[1. 1. 1.]


In [ ]:
x= np.array([2,3,4])
np.ones(x.shape[0])


array([1., 1., 1.])

In [ ]:
[np.ones(len(x))]

[array([1., 1., 1.])]

In [ ]:
x = x[: , None]

In [ ]:
x

array([[2],
       [3],
       [4]])

In [ ]:
x.ndim

2

In [ ]:
x.T

array([[2, 3, 4]])

In [ ]:
x.shape

(3, 1)

In [ ]:
features = np.column_stack((np.ones(x.shape[0]) , x))

In [ ]:
features

array([[1., 2.],
       [1., 3.],
       [1., 4.]])

In [ ]:
y_actual = [1,2,3,4,5]
y_pred = [1.6,2.5,2.9,3,4.1]
 
RMSE = np.sqrt(np.square(np.subtract(y_actual,y_pred)).mean()) 
print("Root Mean Square Error:\n")
print(RMSE)

Root Mean Square Error:

0.6971370023173351


# MLT WEEK 4

In [ ]:
tp = np.where((y_actual == 1) & (y_pred == 1), 1, 0).sum()
tn = np.where((y_actual == 0) & (y_pred == 0), 1, 0).sum()
fp = np.where((y_actual == 0) & (y_pred == 1), 1, 0).sum()
fn = np.where((y_actual == 1) & (y_pred == 0), 1, 0).sum()
label = 1
tp = np.sum((y==label) & (yhat ==labe))

def precision(tp, fp):
    if (tp + fp) == 0:
        return None
    return tp / (tp + fp)

def recall(tp, fn):
    if (tp + fn) == 0:
        return None
    return tp / (tp + fn)

def accuracy(tp, tn, fp, fn):
    return (tp + tn) / (tp + tn + fp + fn)

def f1_score(pr, r):
    return 2 * ((pr * r) / (pr + r))

In [ ]:
def OneHotEncode(y):
  y = np.array([y])
  x = np.zeros((y.size , np.max(y)+1))
  x[np.arange(y.size) , y]= 1
  Ans = x
  return Ans

class LeastSquareClassification(object):
  def __init__(self):
    self.t0=20
    self.t1=1000
  
  def predict(self,X):
    return np.argmax(X @ self.w, axis=-1)

  def predict_internal(self,X):
    return X @ self.w
  
  def loss(self,X,y,reg_rate):
    y_hat = self.predict_internal(X)
    err = y_hat - y
    return (1/2) * (err.T @ err) + (reg_rate / 2) * (self.w.T @ self.w)

  def fit(self,X, y, reg_rate=0):
    self.w = np.linalg.solve(X.T @ X + reg_rate * np.eye(X.shape[-1]), X.T@y)
    print(X.shape, y.shape, self.w.shape)
    return self.w
  
  def calculate_gradient(self, X, y, reg_rate):
    y_hat = self.predict_internal(X)
    return X.T @ (y_hat - y) + reg_rate * self.w
  
  def weight_updates(self, grad,lr):
    return (self.w - lr*grad)

# PERCEPTRON

def predict(x, w):
    z = x@w
    return np.where(z>=0 , 1 , -1)

def percep_loss(x,w,y):
    loss = np.maximum(-1*predict(x,w)*y , np.zeros(x.shape[0]))
    return loss 

# optimization w_new = w + lr * (y-yhat) * transformed_x     

def update(x,w,y,epochs):
  w_new = np.zeros((epochs+1,w.size))
  for i in np.arange(epochs):
    
    for xi, yi in zip(x, y):              
        w = w + 1 * (yi - np.where(xi @ w >=0, 1, -1))*xi
    w_new[i+1] = w
  return w_new 

# linearly separable 

def is_linearly_separable(x,y):
  
  def loss(x, y, w):

    e = np.where(x @ w >=0, 1, -1) - y    
    return (e.transpose() @ e) 

  w = np.zeros(x.shape[1])
  state = False
  for i in np.arange(5):
    for xi, yi in zip(x, y):                 
      w = w + 0.5 * (yi - np.where(xi @ w >=0, 1, -1))*xi
    
    if loss(x,y,w) == 0.0:
      state = True
    
      
  return state
  



In [ ]:
is_linearly_separable(x,y)

False

In [ ]:
def loss(x , y , w):
  w = np.zeros(x.shape[1])
  for i in np.arange(5):
    for xi, yi in zip(x, y):                 
      w = w + 0.5 * (yi - np.where(xi @ w >=0, 1, -1))*xi
    print(w)  


In [ ]:
loss(x , y , w)

[11. 14.]
[22. 28.]
[33. 42.]
[44. 56.]
[55. 70.]


In [ ]:
def loss(x , y ,w ,reg_rate):
  np.sum(np.max(-1 * (x @ w) * y , np.zeros(y.shape[0])))
def loss1(x, y, w):
  e = np.where(x @ w >=0, 1, -1) - y    
  return (e.T @ e)  

In [ ]:
loss1(x , y ,w )

14

In [ ]:
x = np.array([[1,2,] , [3,4] , [5,6]])
w = np.array([1,2])
y = np.array([2,3,4])


In [ ]:
 for i in np.arange(5):
   print(i)

0
1
2
3
4


In [ ]:
update(x,w,y,5)

array([[  0.,   0.],
       [243., 310.],
       [265., 338.],
       [287., 366.],
       [309., 394.],
       [331., 422.]])

In [ ]:
update2(x,w,y,5)

array([[  0.,   0.],
       [353., 450.],
       [375., 478.],
       [397., 506.],
       [419., 534.],
       [441., 562.]])

In [ ]:
update1(x , w , y , 5)

[array([456, 580]),
 array([456, 580]),
 array([456, 580]),
 array([456, 580]),
 array([456, 580])]

In [ ]:
y = [1,2,3,4,5]
y = np.array([y])

In [ ]:
x = np.zeros((y.size , np.max(y)+1))
y.size

5

In [ ]:
np.max(y)+1

6

In [ ]:
x

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
x[np.arange(y.size) , y]= 1

In [ ]:
x

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.arange(y.size)

array([0, 1, 2, 3, 4])

In [ ]:
x[np.arange(y.size) , y]

array([[0., 0., 0., 0., 0.]])

In [ ]:
x[np.array([0, 1, 2, 3, 4]) ,np.array([1,2,3,4,5])] = 1

In [ ]:
x

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])