<a href="https://colab.research.google.com/github/SejalJadhav1/python_/blob/main/MachineLearningTechnique_practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **WEEK 7**

In [ ]:
import numpy as np
from scipy import stats

In [ ]:
def one_hot_encoding(k , y):
  encode = np.zeros((len(y), k))
  encode[np.arange(len(y)), y] = 1
  return encode

def linear_combination(x,w,b):
  return x@w+b

# for softmax : 1.linear combination (z) 2. exp(z)/sum(exp(z))
def softmax(z):
  exp = np.exp(z- np.max(z))
  for i in range(len(z)):
    exp[i] = exp[i]/np.sum(exp[i])
  return exp  

def Euclidean_dist(x1,x2):
  dist = np.sum((x1-x2)**2 , axis = 1)
  return dist

def Manhattan_dist(x1,x2):
  dist = np.sum(np.abs(x1-x2), axis = 1)  
  return dist

class KNN:
  def __init__(self , k , distance_metric= Euclidean_dist , task_type = "Classification" ):
    self.k = k
    self.distance_metric= distance_metric
    self.task_type = task_type

  def fit(self , x , y):
    self.x = x
    self.y = y

  def predict(self, New_example):
    distance_vector = self.distance_metric(self.x , New_example) # distance between the new example and every example from the data
    k_nearest_neighbours_indices = np.argpartition(distance_vector, self.k)[:self.k]
    k_nearest_neighbours = self.y[k_nearest_neighbours_indices]

    if self.task_type == "Classification":
      label = stats.mode(k_nearest_neighbours)[0]
    else:
      label = k_nearest_neighbours.mean()  
    return label  

    



In [ ]:
stats.mode(y)

NameError: ignored

In [ ]:
stats.mode(k_nearest_neighbors)[0]

In [ ]:
z = np.array([[1,2,7], [3,4,7]])

In [ ]:
softmax1(z)

In [ ]:
softmax(z)

In [ ]:
np.arange(len(y))

In [ ]:
y = np.array([1,2,3,1,0])

In [ ]:
stats.mode(y)

In [ ]:
one_hot_encoding(4 , y)

# WEEK 8

In [ ]:
class fit_softSVM: # graded 1
    def __init__(self, C=1):
        self.C = C
        self.w = None
        self.b = None
        
    def decision_function(self,x):
        return x.dot(self.w) + self.b
        
    def cost(self, margin):
        return(1/2)*self.w.dot(self.w)+ self.C*np.sum(np.maximum(0,1-margin))
    
    def margin(self,x,y):
        return y*self.decision_function(x)
    
    def fit(self, x , y , lr=0.001, epochs = 100):
        self.n, self.d = x.shape
        self.w = np.random.randn(self.d)
        self.b = 0
        for _ in range(epochs):
            margin = self.margin(x,y)
            misclassified_pts_idx = np.where(margin<1)[0]
            d_w = self.w - self.C*y[misclassified_pts_idx].dot(x[misclassified_pts_idx])
            self.w = self.w- lr*d_w
            d_b = -self.C*np.sum(y[misclassified_pts_idx])
            self.b = self.b - lr*d_b
        self.support_vec = np.where(self.margin(x,y) <=1)[0]
    
    def predict(self, x):
        return np.sign(self.decision_function(x))
        

def compute_accuracy(x_train, y_train, x_test,  y_test):
    svm = fit_softSVM(15)
    svm.fit(x_train, y_train)
    y_pred = svm.predict(x_test)
    return np.mean(y_test ==y_pred)
    


In [ ]:
def decision_function(x,w,b):
  return x@w + b

def margin(x,y, w ,b):
  return y * (x@w + b)

def loss(x, y, w , b, C):
  0.5 * (w @ w)  + C * np.sum(np.maximum(1-(y*(x@w + b)), 0))

def fit(x, y, b, w, C, lr):
  missclassified_pts_index = np.where((y * (x@w + b)) < 1)[0]
  derivative_w = w + C * np.sum((y[missclassified_pts_index]) @ (x[missclassified_pts_index]))
  w = w - lr * derivative_w

  derivative_b = C * np.sum(y[missclassified_pts_index])
  b = b- lr * derivative_b

  support_vectors = np.where(margin = 1)[0]

def predict(x, w, b):
  return np.sign(x@w + b)

def score(x , y ,b, w):
  p = np.sign(x@w + b)
  return np.mean(y==p)  

def rbf_kernel(sigma, X1, X2):
  return np.exp(-(1/sigma ** 2) * np.linalg.norm(X1[:, np.newaxis] - X2[np.newaxis, :], axis=2) ** 2)
    
def polynomial_kernel(X1, X2 , C ,  degree):
  return (C + X1 @ (X2.T)) ** degree  

def __decision_function( X , alpha , b ,y ,kernel,C ,  degree, sigma, x1, x2  ):
  if kernel== "rbf":
    kernel = rbf_kernel(sigma, x1, x2)
  else: 
    kernel = polynomial_kernel(x1, x2)  
  return (alpha * y ) @ (kernel(x1, x2)) + b
  
def predict( X):
  return np.sign(decision_function(X))

def score( X, y):
  y_hat =predict(X)
  return np.maen(y == y_hat)

In [ ]:
import numpy as np # graded 2
def fit(X_train,Y_train,X_test,Y_test,n_iters=100,lr=0.1):
        
  n_samples, n_features = X.shape
  w = np.zeros(n_features)
  b = 0  

  for _ in range(n_iters):
    for idx, x_i in enumerate(X):
      condition = Y[idx] * (np.dot(x_i, w) - b) >= 1  
      if condition: 
        pass
      else:
        
        w -= lr*np.dot(x_i, Y[idx])
        b -= lr * Y[idx]

  approx = np.dot(X_test, w) - b
  y_pred=np.sign(approx)

  accuracy = np.sum(y_pred == Y_test)/X.shape[0]

  return accuracy

In [ ]:
y = np.array([-1,1,-3])
p = np.array([1,1,1])

In [ ]:
np.sign(y)

In [ ]:
np.mean(y==p)

In [ ]:
y==p

In [ ]:
1/3

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame([['overcast', 'hot', 'high', 'FALSE', 'yes'],
['overcast', 'cool', 'normal', 'TRUE', 'yes'],
['overcast', 'mild', 'high', 'TRUE', 'yes'],
['overcast', 'hot', 'normal', 'FALSE', 'yes'],
['rainy', 'mild', 'high', 'FALSE', 'yes'],
['rainy', 'cool', 'normal', 'FALSE', 'yes'],
['rainy', 'cool', 'normal', 'TRUE', 'no'],
['rainy', 'mild', 'normal', 'FALSE', 'yes'],
['rainy', 'mild', 'high', 'TRUE', 'no'],
['sunny', 'hot', 'high', 'FALSE', 'no'],
['sunny', 'hot', 'high', 'TRUE', 'no'],
['sunny', 'mild', 'high', 'FALSE', 'no'],
['sunny', 'cool', 'normal', 'FALSE', 'yes'],
['sunny', 'mild', 'normal', 'TRUE', 'yes']], columns=['outlook','temp','humidity','windy','play'])

In [ ]:
df.keys()[-1]

# WEEK 9

In [ ]:
eps = np.finfo(float).eps

def entropy_whole(df): # entropy of target column
  target = df.keys()[-1] # column name of the target
  overall_entropy = 0
  values_in_target = df[target].unique() # unique labels in target

  for i in values_in_target:
    p = df[target].value_counts(i)/len(df[target]) 
    overall_entropy += -p * np.log2(p) # -p * log2(p)
  return overall_entropy 

def entropy_attribute(df , attribute):
  target = df.keys()[-1]
  overall_entropy = 0
  values_in_target = df[target].unique() # yes and no
  values_in_attribute = df[attribute].unique() # attribute = humidity	 => high , normal

  entropy_attribute = 0

  for i in values_in_attribute: # high, normal
    overall_entropy = 0

    for j in values_in_target: # yes and no
      num = len(df[attribute][df[attribute]==i][df[target]==j]) # humidity => humidity == high ==> high == yes and high==no
      den = len(df[attribute][df[attribute]==i]) # high 
      p = num/(den+eps)
      overall_entropy += -p*np.log2(p+eps)   # p for high==yes + p for high ==no
    p2 = den/len(df)  # high / no.examples
    entropy_attribute += -p2*overall_entropy
  return abs(entropy_attribute)    

def best_attribute(df):
  ig = []
  attribute_names = df.keys()[:-1]

  for i in attribute_names:
    ig.append(entropy_whole(df)-entropy_attribute(df,i))

  idx_best_attr = np.argmax(ig)
  best_attr = attribute_names[idx_best_attr]

  return best_attr

node = best_attribute(df)  

def buildTree(df, tree=None):
    target = df.keys()[-1]
    node = best_attribute(df)
    attValue = np.unique(df[node])
    if tree is None:
        tree = {}
        tree[node] = {}
    for value in attValue:
        subtable = df[df[node] == value].reset_index(drop=True)
        clValue, counts = np.unique(subtable['play'], return_counts=True)
        if len(counts) == 1: #Checking purity of subset
            tree[node][value] = clValue[0]
        else:
            tree[node][value] = buildTree(subtable) # Calling the function recusively
    return tree

buildTree(df)


In [ ]:
import numpy as np

In [ ]:
 np.unique(df["outlook"])

array(['overcast', 'rainy', 'sunny'], dtype=object)

In [ ]:
tree = {}
tree[node] = {}

In [ ]:
tree

{'outlook': {}}

In [ ]:
hey = {}

In [ ]:
hey["2"] = 2

In [ ]:
hey

{'2': 2}

# WEEK 10 

In [ ]:
import numpy as np
import pandas as pd
from collections import Counter
from sklearn.tree import DecisionTreeClassifier


In [ ]:
def bag(x,y):
  n_samples = x.shape[0]
  indices = np.random.choice(n_samples, size = n_samples, replace = True)
  return x[indices], y[indices]

def most_common_label(y):
  counter = Counter(y)
  most_common = counter.most_common(1)[0][0]
  return most_common  

class RandomForest:
  def __init__(self , n_trees = 10 , min_samples_split = 2 ,max_depth = 100,
               max_features = None):
    self.n_trees = n_trees
    self.min_samples_split = min_samples_split
    self.max_depth = max_depth
    self.max_features = max_features

  def fit(self, x ,y):
    self.trees = []
    for _ in range(self.n_trees):
      tree = DecisionTreeClassifier( min_samples_split = self.min_samples_split, max_depth = self.max_depth,
                                      max_features= self.max_features) # object
      x_sample, y_sample = bag(x,y)
      tree.fit(x_sample, y_sample)
      self.trees.append(tree)

  def predict(self, x):
    # x is an input for which we want a prediction (y) made by our model
    tree_predict = np.array([tree.predict(x) for i in self.trees])   
    tree_predict = np.swapaxes(tree_predict, 0,1)
    y_pred = [most_common_label(i) for i in tree_predict]
    return np.array(y_pred)

  def accuracy(y_actual, y_pred):
    accuracy = len(y_actual==y_pred)/len(y_actual)
    return accuracy

  def Grad_boost(x_train, x_test , y_train, y_test, boosting_rounds, learning_rate = 0.1)):
    y_train_hat = np.repeat(np.mean(y_train) , len(y_train))
    y_test_hat = np.repeat(np.mean(y_train), len(y_train))

    residuals = y_train - y_train_hat
    for i in range(boosting_rounds):
      model = model.fit(x_train , residuals) #object
      y_train_hat += learning_rate * model.predict(x_train) 
      y_test_hat += learning_rate * model.predict(x_test)
      residuals = y_train - y_train_hat
    return y_train_hat, y_test_hat 




Accuracy:  0.956140350877193


In [ ]:
cluster_count = 3

from sklearn.datasets._samples_generator import make_blobs

x, y_true = make_blobs(n_samples = 100,
                        centers = cluster_count,
                        cluster_std = 0.55,
                        random_state = 0) 


In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
import numpy as np

from scipy.spatial.distance import cdist
from sklearn.datasets import make_blobs
centroids = x[np.random.randint(0 , x.shape[0] , size = 3 )]


In [ ]:
labels = np.argmin(cdist(X, centroids), axis=1)
len(labels)
labels

array([0, 2, 0, 2, 2, 2, 1, 0, 0, 2, 2, 2, 0, 2, 1, 2, 1, 2, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 2, 2, 0, 2, 1, 0, 2, 0, 0, 1, 0, 0, 0, 2,
       2, 2, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 1, 1, 0, 1, 0,
       2, 1, 0, 2, 0, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2, 2, 0, 2, 0, 2, 2, 2,
       0, 2, 0, 0, 0, 1, 1, 0, 2, 2, 0, 1])

In [ ]:
cdist(X, centroids)

array([[4.10459981, 4.91036964, 4.46508959],
       [2.07091141, 3.21912189, 0.29115877],
       [4.25888419, 5.088251  , 4.53852189],
       [1.55755109, 2.70676437, 0.57970932],
       [1.48355824, 2.69377169, 1.21383862],
       [2.22271277, 3.40502166, 0.60365607],
       [1.21129218, 0.        , 3.19366163],
       [0.12811378, 1.18893672, 2.18762087],
       [3.96959442, 4.83975917, 4.19519634],
       [1.93329859, 3.12975634, 0.71344076],
       [2.71870033, 3.92176245, 1.14690941],
       [3.26357526, 4.44502975, 1.38554676],
       [4.51058032, 5.18292396, 5.09776444],
       [3.48416828, 4.66342249, 1.57861571],
       [1.11171782, 0.30780487, 3.17634936],
       [4.44003386, 5.39475452, 4.35179488],
       [0.7785413 , 0.59015704, 2.86985752],
       [1.57132437, 2.77108529, 1.39814396],
       [0.94036665, 1.32368813, 2.04637375],
       [1.12349013, 0.27053167, 3.00824276],
       [1.64173093, 1.02042004, 3.73101559],
       [0.97343927, 0.72994245, 3.06623033],
       [1.

# WEEK 11

In [ ]:
def fit(X, k):
    # Take k random points from data set and take them as initial centroids
    centroids = X[np.random.randint(0, X.shape[0], size=k)]

    #calculate initial label for each data point
    labels = np.argmin(cdist(X, centroids), axis=1)

    for _iteration in range(10):
        # copy labels for all points for comparing later
        previous_labels = labels.copy()

        # compute new centroids
        centroids = np.array([np.mean(X[labels==r], axis=0) for r in range(k)])

        # at last recalculate label for each data point
        labels = np.argmin(cdist(X, centroids), axis=1)

        # Check if labels of points are not changing
        if all(labels == previous_labels):
            break

    return centroids, labels


In [ ]:
def fit(x, k):
  centroid = x[np.random.randint(0 , x.shape[0], size = k)]
  labels = np.argmin(cdist(x, centroid), axis = 1)

  for i in range(10):
    previous_labels = labels.copy()

    centroid = np.array([np.mean(x[labels == i], axis = 0) for i in range(k)])

    labels = np.argmin(cdist(x , centroid), axis = 1)

    if all(labels == previous_labels):
      break

  return centroid , labels    


In [ ]:
fit(x, 3)

(array([[ 0.84271525,  4.22277007],
        [ 2.10149963,  1.14741919],
        [-1.64169636,  2.85917392]]),
 array([1, 0, 1, 0, 0, 0, 2, 2, 1, 0, 0, 0, 1, 0, 2, 1, 2, 0, 2, 2, 2, 2,
        2, 0, 1, 1, 1, 1, 2, 2, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 2, 1, 1, 0,
        0, 0, 1, 1, 2, 2, 0, 1, 0, 1, 2, 2, 1, 1, 0, 1, 1, 2, 2, 2, 2, 1,
        0, 2, 1, 0, 2, 0, 0, 1, 1, 0, 0, 0, 2, 1, 0, 0, 1, 0, 1, 0, 0, 0,
        1, 0, 1, 1, 2, 2, 2, 2, 0, 0, 2, 2]))

In [ ]:
centroids = np.array(x[np.mean([labels==r], axis=0) for r in range(3)])
centroids

array([[ 0.97677291,  1.77827698],
       [-1.97828227,  2.77526744],
       [ 1.09644934,  4.07676089]])